---
ENVIRONMENT: # Root key to define the environment program properties
  VIPER_CONFIG: default # The profile that contains the configuration to be overwritten from system env
  VERBOSE: false # Log level (verbose=true means debug mode)
  # STRICT: true = strict mode on, otherwise off, will exit the program if the go resty returns an error in STRICT mode enabled,
  # be it client error, server error or other. Turning off STRICT mode will simply warn of client/server errors with no exit program.
  STRICT: true
  ONLY_CONFIG: false # this property is to have control on the program to print the configuration only without run the main program
  # SAPIG
  # core: base sapig
  # ob: Open Banking specification of sapig
  SAPIGTYPE: core  
  # TYPE: It can be the values set on platform constants (@See constants.go), currently CDK or CDM
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC (Forgerock Identity Cloud) identity cloud platform
  CLOUDTYPE: CDKs
  NAMESPACE: dev # Root key to get the namespace/environment to populate the user data
  PATHS:
    CONFIG_AUTH_HELPER: config/defaults/auth-helper/  # Path for json to help with auth on FIdC platform
HOSTS:
  RS_BASE_URI: http://test-facility-bank:8080 # Base URI for RS API
  IDENTITY_PLATFORM_FQDN: iam.dev.forgerock.financial # Identity platform Host name
  SCHEME: https # URI scheme, Syntax part of a generic URI
IDENTITY: # Root key for parameter values related with identity platform configuration
  AM_REALM: alpha # The realm used for secure banking
USERS: # Root key users to be created or to authenticate and authorize flows
  FR_PLATFORM_SERVICE_ACCOUNT_ID: replace-me # Service Account ID (must exist previously)
  FR_PLATFORM_SERVICE_ACCOUNT_KEY: replace-me # Service Account Private Key (must exist previously)
  PSU_USER_ID: 4737f9f9-fa0a-4159-bc61-7da31542e624 # Psu User Id to (It will be created): needs to be a UUID
  PSU_USERNAME: psu4test # Psu Username to (It will be created)
  PSU_PASSWORD: 0penBanking! # Psu user password (It will be created)
