---
ENVIRONMENT: # Root key to define the environment program properties
  VIPER_CONFIG: default # The profile that contains the configuration to be overwritten from system env
  VERBOSE: false # Log level (verbose=true means debug mode)
  # STRICT: true = strict mode on, otherwise off, will exit the program if the go resty returns an error in STRICT mode enabled,
  # be it client error, server error or other. Turning off STRICT mode will simply warn of client/server errors with no exit program.
  STRICT: true
  ONLY_CONFIG: false # this property is to have control on the program to print the configuration only without run the main program
  # TYPE: It can be the values set on platform constants (@See constants.go), currently CDK or CDM
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC (Forgerock Identity Cloud) identity cloud platform
  TYPE: CDK
  PATHS: # Key to define the paths for files to populate configuration data to the platform
    CONFIG_BASE_DIRECTORY: config/defaults/ # Base configuration path folder
    CONFIG_SECURE_BANKING: config/defaults/secure-open-banking/ # Path folder for secure banking
    CONFIG_IDENTITY_PLATFORM: config/defaults/identity-platform/ # Path folder for generic platform configuration
HOSTS:
  RS_FQDN: rs.dev.forgerock.financial # RS host name
  IDENTITY_PLATFORM_FQDN: iam.joycegilding-forgerock.forgerock.financial # Identity platform Host name
  SCHEME: https # URI scheme, Syntax part of a generic URI
USERS: # Root key users to be created or to authenticate and authorize flows
  FR_PLATFORM_ADMIN_USERNAME: amadmin # Identity platform Username with admin grants (must exist previously)
  FR_PLATFORM_ADMIN_PASSWORD: Ny1gtep8shAjsbBIMGEuDpeH # Identity platform User password with admin grants (must exist previously)
  PSU_USERNAME: psu4test # Psu Username to (It will be created)
  PSU_PASSWORD: 0penBanking! # Psu user password (It will be created)
NAMESPACE: joycegilding-forgerock # Root key to get the namespace/environment to populate the user data
