{{- if eq .Values.environment.fr_platform.type "FIDC" }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: initializer-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.projectId }}
  data:
    - key: {{ .Release.Namespace}}-cdm-admin-password
      name: cdm-admin-password
      version: latest
    - key: {{ .Release.Namespace}}-cdm-admin-user
      name: cdm-admin-user
      version: latest
{{ end }}
