---
{{- if eq .Values.deployment.type "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.seccessfulJobHistoryLimit}}
  startingDeadlineSeconds: {{. Values.cronjob.startingDeadlineSeconds}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.cronjob.image.repo }}:{{ default .Chart.AppVersion .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.imagePullPolicy }}
              env:
                - name: ENVIRONMENT.STRICT
                  value: {{ .Values.cronjob.environment.strict | quote }}
                - name: ENVIRONMENT.TYPE
                  valueFrom:
                    configMapKeyRef:
                      name: deployment-config
                      key: ENVIRONMENT_TYPE
                - name: IDENTITY_PLATFORM_FQDN # variable to run the command shell, the shell doesn't support variables with dot.
                  valueFrom:
                    configMapKeyRef:
                      name: deployment-config
                      key: IDENTITY_PLATFORM_FQDN
                - name: HOSTS.IDENTITY_PLATFORM_FQDN
                  valueFrom:
                    configMapKeyRef:
                      name: deployment-config
                      key: IDENTITY_PLATFORM_FQDN
                {{- if eq .Values.environment.frPlatformType "FIDC" }}
                - name: USERS.FR_PLATFORM_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: initializer-secret
                      key: cdm-admin-password             
                - name: USERS.FR_PLATFORM_ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: initializer-secret
                      key: cdm-admin-user
                {{- else }}
                - name: USERS.FR_PLATFORM_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: am-env-secrets
                      key: AM_PASSWORDS_AMADMIN_CLEAR
                {{ end }}              
                - name: NAMESPACE
                  value: {{ .Values.cronjob.namespace }}
              command: [ "/bin/sh", "-c" ]
              args:
                - |                 
                  echo "IDENTITY_PLATFORM_FQDN $IDENTITY_PLATFORM_FQDN"
                  until $(curl -X GET --output /dev/null --silent --head --fail -H "X-OpenIDM-Username: anonymous" \
                  -H "X-OpenIDM-Password: anonymous" -H "X-OpenIDM-NoSession: true" \
                  https://$IDENTITY_PLATFORM_FQDN/openidm/info/ping)
                  do
                  echo "IDM not ready"
                  sleep 10
                  done
                  ./initialize
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
{{ end }}