---
{{- if eq .Values.deployment.type "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
spec:
  template:
    metadata:
      labels:
        appversion: {{ .Chart.AppVersion }}
        chartversion: {{ .Chart.Version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.job.image.repo }}:{{ default .Chart.AppVersion .Values.job.image.tag }}"
          imagePullPolicy: {{ .Values.job.image.imagePullPolicy }}
          env:
            - name: ENVIRONMENT.STRICT
              value: {{ .Values.job.environment.strict | quote }}
            - name: ENVIRONMENT.TYPE
              valueFrom:
                configMapKeyRef:
                  name: core-deployment-config
                  key: CLOUD_TYPE
            - name: IDENTITY_PLATFORM_FQDN # variable to run the command shell, the shell doesn't support variables with dot.
              valueFrom:
                configMapKeyRef:
                  name: core-deployment-config
                  key: IDENTITY_PLATFORM_FQDN
            - name: HOSTS.IDENTITY_PLATFORM_FQDN
              valueFrom:
                configMapKeyRef:
                  name: core-deployment-config
                  key: IDENTITY_PLATFORM_FQDN
            {{- if eq .Values.job.environment.frPlatformType "FIDC" }}
            - name: USERS.FR_PLATFORM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: initializer-secret
                  key: cdm-admin-password             
            - name: USERS.FR_PLATFORM_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: initializer-secret
                  key: cdm-admin-user
            {{- else }}
            - name: USERS.FR_PLATFORM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: am-env-secrets
                  key: AM_PASSWORDS_AMADMIN_CLEAR
            {{ end }}              
            - name: NAMESPACE
              value: {{ .Values.job.namespace }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |                 
              echo "IDENTITY_PLATFORM_FQDN $IDENTITY_PLATFORM_FQDN"
              until $(curl -X GET --output /dev/null --silent --head --fail -H "X-OpenIDM-Username: anonymous" \
              -H "X-OpenIDM-Password: anonymous" -H "X-OpenIDM-NoSession: true" \
              https://$IDENTITY_PLATFORM_FQDN/openidm/info/ping)
              do
              echo "IDM not ready"
              sleep 10
              done
              ./initialize
      restartPolicy: {{ .Values.job.restartPolicy }}
  backoffLimit: {{ .Values.job.backoffLimit }}
{{ end }}
