name: pr

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: test-user-account-creator
  PR_NUMBER: pr-${{ github.event.number }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: |
          make test-ci

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

        # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker

      - name: docker build
        run: |
          make docker tag=${{ env.PR_NUMBER }}

      - name: Create lowercase Github Username
        id: toLowerCase
        run: echo "GITHUB_USER=$(echo ${{github.actor}} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: 'Deploy Service'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v TAG=${{ env.PR_NUMBER }} -v ARGO_VALUES_PREFIX=testUserAccountCreator -v SERVICE_NAME=test-user-account-creator -v ENVIRONMENT=${{ env.GITHUB_USER }} -v BRANCH=${{ github.head_ref }}'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/service-build'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          TRIGGER_NAME: github-actions-trigger-test-data
        id: run-pipeline